// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://durgdrjiekfbbadkheay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1cmdkcmppZWtmYmJhZGtoZWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjA2MzIsImV4cCI6MjA2NDEzNjYzMn0.tWtqT0CkW3ol6KdYKb2KOo4QUTc7yuKHGqwSUs7J4qI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);